#! /bin/bash

set -eu -o pipefail

DATA_DIR="${DATA_DIR:-./data}"

usage() {
    echo "usage: $0 [upload|download] google_cloud_storage_url"
    echo
    echo "google_cloud_storage_url is a gs:// URL to a directory where archived"
    echo "stores will be stored to and retrieved from."
    exit 1
}

if [ $# -ne 2 ]; then
    echo "expected 2 parameters"
    echo ""
    usage
fi

# CockroachDB nodes are named blah-cockroach-[0-9]*, so extract the final
# numeric part.
gcs_url=$2
hostname=$(hostname)
node_index=${hostname##*-} # remove everything through the final '-' in the hostname
store_url="${gcs_url}/store${node_index}.tgz"

action=$1
case $action in
upload)
    echo "Uploading store ${DATA_DIR} to ${store_url}"
    tar zcvf - ${DATA_DIR} | gsutil cp - ${store_url}
    ;;
download)
    echo "Downloading ${store_url} to store ${DATA_DIR}"
    if [ -d ${DATA_DIR} ]; then
        backup_dir="${DATA_DIR}.$(date +%Y%m%d-%H%M%S)"
        echo "Backing up ${DATA_DIR} to ${backup_dir}"
        mv "${DATA_DIR}" "${backup_dir}"
    fi
    gsutil cat ${store_url} | pv --bytes | tar zxf -
    ;;
*)
    echo "Unknown action '${action}'"
    echo
    usage
esac
